spark.submit.deployMode: 'client'
spark.shuffle.encryption.enabled: 'false'
spark.sql.hive.convertMetastoreOrc: 'true'
spark.sql.repl.eagerEval.enabled: 'true'
spark.default.parallelism: '800'
spark.sql.execution.arrow.pyspark.fallback.enabled: 'true'
spark.sql.execution.arrow.pyspark.enabled: 'true'
spark.sql.execution.arrow.maxRecordsPerBatch: '10000'
spark.kryoserializer.buffer: '512m'
spark.kryoserializer.buffer.max: '2047m'
spark.rpc.message.maxSize: '2047'
hive.exec.dynamic.partition: 'true'
hive.exec.dynamic.partition.mode: 'nonstrict'

